version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

    ports:
      - 3002:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456